import './App.css';
import HorizontalTimeline, { pointEvent, rangeEvent, spacer, top } from "./HorizontalTimeline";

export default function App2() {
  return (
    <HorizontalTimeline
      startYear={1730}
      endYear={1820}
      centerYear={1750}
      pixelsPerYear={20}
      events={[
        rangeEvent('War of Jenkins\' Ear', [1739, 10, 22], [1742], 'The British (King George II) and Spanish (King Philip V) Empires go to war in the Americas over economic access and an attack on a British sea captain. The war is subsumed into the War of the Austrian Succession.'),
        pointEvent('HRE Charles VI (Habsburg) dies', [1740, 10, 20], 'Charles VI (Habsburg), Holy Roman Emperor, dies without a male heir leading to the War of Austrian Succession.'),
        rangeEvent('War of the Austrian Succession', [1740, 2, 16], [1748, 10, 18], 'The end of the main Habsburg male line results in Prussia, France, Spain, Bavaria, Sweden, etc. going to war with Austria, Great Britain, Russia, the Dutch Republic, etc. Fronts are in Germany, Italy and the Netherlands.'),
        rangeEvent('First Silesian War', [1740, 2, 16], [1742, 6, 11], 'Prussia (Frederick the Great) seizes most of Silesia from Austria (Maria Theresa Habsburg) as part of the War of Austrian Succession.'),
        rangeEvent('Russo-Swedish War', [1741, 8, 8], [1743, 8, 18], 'Sweden, avenging the assassination of a diplomat and eager to regain lost land, wages an unsuccessful war with Russia, mostly within Finland.'),
        rangeEvent('King George\'s War', [1744, 5, 3], [1748, 10, 18], 'When Great Britain (King George II) and France (King Louis XV) join the War of the Austrian Succession, the conflict spreads to New England and Canada.'),
        rangeEvent('Second Silesian War', [1744, 8, 7], [1745, 12, 25], 'Shortly after the First Silesian War, Prussia (Frederick the Great) retains most of Silesia after an attack from Austria (Maria Theresa Habsburg) and Saxony as part of the War of Austrian Succession.'),
        rangeEvent('Jacobite rising', [1745, 8, 19], [1746, 4, 20], 'With much of Great Britain\'s army on the continent fighting the War of the Austrian Succession, French-backed Jacobites launch a rebellion attempting to restore the Stuarts to the British throne.'),
        rangeEvent('First Carnatic War', [1746, 7, 6], [1748, 10, 27], 'The British and French conflict during the War of Austrian Succession spreads to India.'),
        rangeEvent('Second Carnatic War', [1749], [1754], 'Even with peace in Europe, Great Britain and France take opposing sides in an Indian succession civil war.'),
        spacer(),
        // rangeEvent('Guarani War', [1754], [1756], 'Portuguese and Spanish forces expel indigenous Guarani Jesuits from Portuguese land in modern-day southern Brazil.'),
        // spacer(),
        rangeEvent('French and Indian War', [1754, 5, 28], [1763, 2, 10], 'Great Britain (Kings George II, George III) and France (King Louis XV) again go to war in North America, both aided by natives, when colonists from both sides clash over territory. The war is subsumed into the Seven Years\' War.'),
        pointEvent('Russian Empress Elizabeth (Romanov) dies', [1762, 1, 5], 'Empress Elizabeth (Romanov), of Russia, dies causing Russia to switch sides in the Seven Years\' War and helping to end the global conflict.'),
        rangeEvent('Seven Years\' War', [1756, 5, 17], [1763, 2, 15], 'Territorial conflicts and realignment of alliances reignites war in Europe, North America and India between Prussia, Great Britain, Portugal etc. and Austria, France, Spain, Sweden, Russia, etc.'),
        rangeEvent('Third Silesian War', [1756, 8, 29], [1763, 2, 15], 'Prussia invades Saxony and defends Silesia from Austria, Russia and Austria\'s new ally, France. The war is subsumed into the Seven Years\' War.'),
        rangeEvent('Third Carnatic War', [1756], [1763], 'The Seven Years\' War spreads to India and Bengal.'),
        rangeEvent('Pomeranian War', [1757, 9, 13], [1762, 5, 22], 'As part of the Seven Years\' War, Sweden attempts to regain lost portions of Pomerania from Prussia but an unprepared army and ally Russia changing sides results in status quo.'),
        rangeEvent('Anglo-Spanish War', [1762, 1, 4], [1763, 2, 10], 'Spain\'s new King Charles III (Bourbon-Anjou) joins the withering French side in the Seven Years\' War leading Great Britain (King George III) to declare war and attack Spanish colonies in North America and the Philippines.'),
        rangeEvent('Fantastic War', [1762, 5, 5], [1763, 2, 10], 'Spain and France launch a disastrous attempt to invade Portugal (also defended by Great Britain) and Portuguese colonies in South America.'),
        spacer(),
        rangeEvent('Pontiac\'s War', [1763, 4, 27], [1766, 7, 25], 'Within months of taking over French lands in North America, British soldiers and colonists are attacked by various Native American tribes unhappy with the change.'),
        spacer(),
        rangeEvent('Russo-Turkish War', [1768, 10, 6], [1774, 7, 21], 'Russia (Catherine the Great) goes to war with the Ottoman Empire (Sultan Mustafa III) over Turkish defense of anti-Russian Poles triggering a partition of Poland-Lithuania and revolts against the Ottomans.'),
        rangeEvent('Danish-Algerian War', [1769], [1772], 'Denmark-Norway goes to war with Ottoman Algeria over piracy in the Mediterranean.'),
        // rangeEvent('Spanish-Algerian War', [1775], [1785], 'Spain, aided by other Mediterranean powers, goes to war with Ottoman Algeria over piracy in the region including two failed bombardments of Algiers.'),
        top(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        rangeEvent('War of the Bavarian Succession', [1778, 7, 3], [1779, 5, 13], 'When Duke Maximilian III Joseph of Bavaria dies childless, Austria (Holy Roman Emperor Joseph II) goes to war with Prussia (Frederick the Great) and Saxony over control of the electorate.'),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        spacer(),
        rangeEvent('Russo-Turkish War', [1787], [1792], 'The Ottoman Empire (Sultan Abdul Hamid I) fails in its attempt to regain lost territory from Russia (Catherine the Great) including Crimea and land around the Black Sea.'),
        rangeEvent('Austro-Turkish War', [1788, 2], [1791, 8, 4], 'Austria (HRE Joseph II, Leopold II) joins Russia in battling the Ottoman Empire (Sultan Abdul Hamid I) for land in eastern and southeastern Europe with inconclusive results.'),
        rangeEvent('Russo-Swedish War', [1788, 6], [1790], 'Sweden (King Gustav III) goes to war with Russia (Catherine the Great) trying to distract them from their victories against the Ottomans and creating a power imbalance.'),
        rangeEvent('Theatre War', [1788, 9, 24], [1789, 7, 9], 'Honoring a treaty with Russia, Denmark-Norway (King Christian VII) briefly goes to war with Sweden (King Gustav III) until the threat of Prussian and British support forces an armistice.'),
        rangeEvent('Polish-Russian War', [1792, 5, 18], [1792, 7, 27], 'In response to a new Polish-Lithuanian constitution, Russia (Catherine the Great) invades both regions resulting in the Second Partition of Poland.'),
        rangeEvent('Kościuszko Uprising', [1794, 3, 24], [1794, 11, 16], 'A failed Polish insurgency against Russia results in Poland being partitioned out of existence for over a century.'),
        top(),
        pointEvent('Boston Massacre', [1770, 3, 5]),
        pointEvent('Boston Tea Party', [1773, 12, 16]),
        rangeEvent('American Revolutionary War', [1775, 4, 19], [1783, 9, 3], 'British colonists in America revolt against Great Britain for independence. Eventually France, Spain and the Dutch Republic join in attacking Britain around the world.'),
        rangeEvent('Anglo-French War', [1778, 6, 17], [1783, 9, 3], 'France, and later Spain, go to war with Great Britain in the Caribbean, Europe and India, taking advantage of the American Revolution.'),
        rangeEvent('Fourth Anglo-Dutch War', [1780, 12], [1784, 5, 20], 'Great Britain goes to war with the Dutch Republic in colonies around the world over its continued dealings with British enemies. The Dutch have to rely on France and Spain and are dealt terrible losses.'),
        rangeEvent('Northwest Indian War', [1786], [1795, 8, 3], 'Native tribes, aided by Great Britain, go to war with the new United States over control of northwest territories from modern-day Ohio to Minnesota'),
        spacer(),
        pointEvent('Storming of the Bastille', [1789, 7, 14]),
        rangeEvent('French Revolution', [1789, 5, 5], [1799, 11, 9]),
        pointEvent('French King Louis XVI executed', [1793, 1, 21]),
        // rangeEvent('Liège Revolution', [1789, 8, 18], [1791, 1, 12]),
        // rangeEvent('Brabant Revolution', [1789, 10, 24], [1790, 12, 3]),
        rangeEvent('War of the First Coalition', [1792, 4, 20], [1797, 10, 17]),
        rangeEvent('War in the Vendée (French Civil War)', [1793, 3, 3], [1796, 7, 16]),
        rangeEvent('War of the Pyrenees (France vs. Spain)', [1793, 3, 7], [1795, 7, 22]),
        rangeEvent('Reign of Terror', [1793, 9, 5], [1794, 7, 27]),
        pointEvent('Robespierre executed', [1794, 7, 28]),
        rangeEvent('French invasion of Switzerland', [1798, 1, 28], [1798, 5, 17], 'France overthrows Switzerland contributing to the formation of the second coalition.'),
        // rangeEvent('Irish Rebellion of 1798', [1798, 5, 24], [1798, 10, 12], 'Inspired by the American and French revolutions, a group in Ireland stages a major but unsuccessful revolt against Great Britain.'),
        rangeEvent('Quasi-War (United States vs. France)', [1798, 7, 7], [1800, 9, 30]),
        rangeEvent('Peasants\' War (Southern Netherlands)', [1798, 10, 12], [1798, 12, 5]),
        rangeEvent('War of the Second Coalition', [1798, 11, 29], [1802, 3, 25]),
        rangeEvent('War of the Third Coalition', [1803, 5, 18], [1806, 7, 18]),
        pointEvent('Napoleon crowns himself Emperor', [1804, 12, 2]),
        pointEvent('Battle of Austerlitz', [1805, 12, 2]),
        pointEvent('Dissolution of the Holy Roman Empire', [1806, 8, 6]),
        rangeEvent('Franco-Swedish War', [1805, 10, 31], [1810, 1, 6]),
        rangeEvent('War of the Fourth Coalition', [1806, 10, 9], [1807, 7, 9]),
        rangeEvent('Finnish War (Russia vs. Sweden)', [1808, 2, 21], [1809, 9, 17]),
        rangeEvent('Dano-Swedish War', [1808, 3, 14], [1809, 12, 10]),
        rangeEvent('Peninsular War (France in Iberia)', [1808, 5, 2], [1814, 4, 17]),
        // spacer(),
        // rangeEvent('Haitian Revolution', [1791, 8, 21], [1804, 1, 1], 'A slave revolt in Saint-Domingue against France and supported by Great Britain and Spain, ended with an independent Haiti'),
        // spacer(),
        // rangeEvent('Prussian invasion of Holland', [1787, 9, 13], [1787, 10, 10], 'Prussia invades the Dutch Republic after the statdholder\'s wife, Wilhelmina, Prussian King Frederick William II\'s sister, is arrested by Dutch revolutionaries.'),
        // rangeEvent('Russo-Persian War', [1804, 6, 22], [1813, 10, 24])
        // rangeEvent('Russo-Turkish War', [1806, 12, 22], [1812, 5, 28])

        // pointEvent('Portuguese monarchy abolished', [1910, 3, 5]),
      ]}
    />
  )
}
